const applications = [
    {
        id: 1,
        Company: 'Rindus',
        Title: 'Backend Software Engineer (Java)',
        Link: 'https://www.linkedin.com/jobs/view/4138312759/?trackingId=Cbd7VEXORpaLPbVgIf0TWg%3D%3D&refId=h3AhdB4kQyu8aiZHHEEccQ%3D%3D&midToken=AQFzRuX2ttPs8Q&midSig=1p3iqJEDdEmrE1&trk=eml-email_application_confirmation_with_nba_01-applied_jobs-0-jobcard_body&trkEmail=eml-email_application_confirmation_with_nba_01-applied_jobs-0-jobcard_body-null-8g3tzy~m72apxyo~7w-null-null&eid=8g3tzy-m72apxyo-7w&otpToken=MTcwNDFlZTcxYTJjYzhjNWI0MjQwNGVkNDUxN2U0YmM4N2NlZDI0NDljYWU4ZjYxNzJjZTA0NmM0YzVjNWFmMWYyZDBkZmE0NDRkNmZlYzM2ZTg0YzBiNWU0YWRkYjZkYmJhZmFjZTFmOTUwYzQ3ODZiZDVlNywxLDE%3D',
        'Applied On': '12-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 2,
        Company: 'BeeHealthy',
        Title: 'Android Developer',
        Link: 'https://mehilainen.wd103.myworkdayjobs.com/en-US/tyomarkkinatori_careers/job/Android-Developer-for-BeeHealthy_R0035076',
        'Applied On': '12-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 3,
        Company: 'CGI',
        Title: 'Sovelluskehittäjä, Titania Classic',
        Link: 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&page=jobdetails&JobID=J0125-2032&applied=y',
        'Applied On': '12-feb',
        Salary: '',
        Status: 'Rejected',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 4,
        Company: 'CGI',
        Title: 'Java developer',
        Link: 'https://cgi.njoyn.com/corp/xweb/xweb.asp?NTKN=c&page=jobdetails&JobID=J1024-1239&applied=y',
        'Applied On': '12-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 5,
        Company: 'Apipana',
        Title: 'Backend Software Engineer (Java)',
        Link: '',
        'Applied On': '10-feb',
        Salary: '40~46',
        Status: 'Waiting',
        'Last Step': 'Phone Call',
        notes: '',
    },
    {
        id: 6,
        Company: 'Mastercard',
        Title: 'Software Engineer-1',
        Link: 'https://careers.mastercard.com/us/en/job/R-236222/Software-Engineer-1',
        'Applied On': '10-feb',
        Salary: '',
        Status: 'Rejected',
        'Last Step': 'Applied',
        notes: 'There is also a Software Engineer-2, what? https://careers.mastercard.com/us/en/job/R-236221/Software-Engineer-2',
    },
    {
        id: 7,
        Company: 'N.World',
        Title: 'Backend (Java)',
        Link: 'https://www.linkedin.com/jobs/view/4138910807/?alternateChannel=search&refId=zp67%2BOsw7HIvKMnpU1fzcA%3D%3D&trackingId=vuH6iEPaGpsx382LCrB2wg%3D%3D',
        'Applied On': '11-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Phone Call',
        notes: 'Not sure if its the link is correct',
    },
    {
        id: 8,
        Company: 'Automattic',
        Title: 'Code Wrangler',
        Link: 'https://automattic.com/work-with-us/job/code-wrangler/?gh_src=9befc4141us',
        'Applied On': '13-feb',
        Salary: '70~170',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 9,
        Company: 'CaixaBank Tech',
        Title: 'Software Engineer Java',
        Link: 'https://caixabanktech.talentclue.com/es/job/112773018',
        'Applied On': '17-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Phone Call',
        notes: '',
    },
    {
        id: 10,
        Company: 'Telko LTD',
        Title: 'Open applicaton*',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 11,
        Company: 'Elomatic',
        Title: 'Open applicaton*',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 12,
        Company: 'F-Secure',
        Title: 'Open applicaton*',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 13,
        Company: 'CSC',
        Title: 'Open applicaton*',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 14,
        Company: 'Konecranes',
        Title: 'Operations Engineer',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 15,
        Company: 'Konecranes',
        Title: 'Development Engineer',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 16,
        Company: 'Konecranes',
        Title: 'Reliability Engineer',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 17,
        Company: 'CSC',
        Title: 'Senior Developer',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 18,
        Company: 'AlphaSense',
        Title: 'Talent Community',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 19,
        Company: 'If...',
        Title: '.NET/Azure Developer',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 20,
        Company: 'If...',
        Title: 'Senior .NET Back-end Developer',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
    {
        id: 21,
        Company: 'Wolt',
        Title: 'Python backend engineer',
        Link: '',
        'Applied On': '20-feb',
        Salary: '',
        Status: 'Waiting',
        'Last Step': 'Applied',
        notes: '',
    },
  ];
 

export default applications;